CREATE TABLE IF NOT EXISTS jobs (
  id VARCHAR(255) PRIMARY KEY,
  command TEXT NOT NULL,
  state VARCHAR(50) NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  max_retries INT NOT NULL DEFAULT 3,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  next_try_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  worker_id VARCHAR(255),
  exit_code INT,
  stdout LONGTEXT,
  stderr LONGTEXT,
  processing_expires_at DATETIME
);

